[package]
name = "demon-bluff-gameplay-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
enum-display-derive = "0.1.1"
itertools = "0.14.0"
serde = { version = "1.0.225", features = ["serde_derive"] }
strum = { version = "0.27.2", features = ["derive"] }
thiserror = "2.0.15"
